### ISSUE TITLE
Pre-requisites

### ISSUE THREAD

**Issue by jackbrumley** [Snuffypot11/Whisper-Dictation#1]
The following might save someone some time. I recommend you put the following on your main readme.

Need to have the following pre-requisites installed:
`pip install pyaudio keyboard requests pyautogui screeninfo pillow pystray`

Also, just in case you need to find it like I did, the config file is stored here:
`C:\Users\<user>\AppData\Local\WhisperDictation\config.ini`

Works well though, great job. Much more reliable than Windows 10/11 dictation. Been thinking of a better way util I used ChatGPT for recommendations and it pointed me at your repo.

**Comment by Snuffypot11** [comment]
thank you @jackbrumley, I've updated the readme.
The Windows 10/11 dictation just wasn't up to scratch for me, exactly why I made this. Hope you and others find it useful.
